// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cleaning-vibes/DarkFocus.tsx": () => import("../components/mockups/cleaning-vibes/DarkFocus.tsx"),
  "./components/mockups/cleaning-vibes/QuietSpace.tsx": () => import("../components/mockups/cleaning-vibes/QuietSpace.tsx"),
  "./components/mockups/cleaning-vibes/WarmNotebook.tsx": () => import("../components/mockups/cleaning-vibes/WarmNotebook.tsx")
};
